/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package extras;

/**
 *
 * @author Gero
 */
public class DescripcionDetalles extends javax.swing.JPanel {

    /**
     * Creates new form DescripcionDetalles
     */
    public DescripcionDetalles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo = new javax.swing.JLabel();
        txtNombrePrincipal = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtTipoPrincipal = new javax.swing.JLabel();
        txtTipo = new javax.swing.JLabel();
        txtDescripcionPrincipal = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JLabel();
        txtNumeroPrincipal = new javax.swing.JLabel();
        txtNumeroIntentos = new javax.swing.JLabel();
        txtImagen = new javax.swing.JLabel();

        setBackground(new java.awt.Color(199, 13, 13));
        setMinimumSize(new java.awt.Dimension(700, 200));
        setPreferredSize(new java.awt.Dimension(700, 200));

        txtTitulo.setFont(new java.awt.Font("Fairview Small Caps", 0, 48)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setText("Detalles de pruebas");

        txtNombrePrincipal.setFont(new java.awt.Font("Fairview Small Caps", 0, 24)); // NOI18N
        txtNombrePrincipal.setForeground(new java.awt.Color(255, 255, 255));
        txtNombrePrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombrePrincipal.setText("Nombre");

        txtNombre.setFont(new java.awt.Font("Fairview Small Caps", 0, 24)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 204, 204));
        txtNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombre.setText("Puteria");

        txtTipoPrincipal.setFont(new java.awt.Font("Fairview Small Caps", 0, 24)); // NOI18N
        txtTipoPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        txtTipoPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTipoPrincipal.setText("Tipo");

        txtTipo.setFont(new java.awt.Font("Fairview Small Caps", 0, 24)); // NOI18N
        txtTipo.setForeground(new java.awt.Color(102, 204, 204));
        txtTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTipo.setText("Pendejada");

        txtDescripcionPrincipal.setFont(new java.awt.Font("Fairview Small Caps", 0, 24)); // NOI18N
        txtDescripcionPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcionPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDescripcionPrincipal.setText("Descripcion");

        txtDescripcion.setFont(new java.awt.Font("Fairview Small Caps", 0, 24)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(102, 204, 204));
        txtDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDescripcion.setText("Blablabla");

        txtNumeroPrincipal.setFont(new java.awt.Font("Fairview Small Caps", 0, 24)); // NOI18N
        txtNumeroPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        txtNumeroPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNumeroPrincipal.setText("Numero de Intentos");

        txtNumeroIntentos.setFont(new java.awt.Font("Fairview Small Caps", 0, 24)); // NOI18N
        txtNumeroIntentos.setForeground(new java.awt.Color(102, 204, 204));
        txtNumeroIntentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNumeroIntentos.setText("01");

        txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/plus423.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtImagen))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombrePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTipoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(txtDescripcionPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(txtNumeroPrincipal)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumeroIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombrePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcionPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNumeroIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel txtDescripcion;
    public javax.swing.JLabel txtDescripcionPrincipal;
    public javax.swing.JLabel txtImagen;
    public javax.swing.JLabel txtNombre;
    public javax.swing.JLabel txtNombrePrincipal;
    public javax.swing.JLabel txtNumeroIntentos;
    public javax.swing.JLabel txtNumeroPrincipal;
    public javax.swing.JLabel txtTipo;
    public javax.swing.JLabel txtTipoPrincipal;
    public javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
