/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package principal;

/**
 *
 * @author Gero
 */
public class Grado extends javax.swing.JDialog {

    /**
     * Creates new form Grado
     */
    public Grado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGrado = new javax.swing.JPanel();
        lblTituloGrados = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        slptGrados = new javax.swing.JSplitPane();
        pnlIGrados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPasarNivel2 = new javax.swing.JButton();
        btnPasarNivel3 = new javax.swing.JButton();
        btnPasarNivel4 = new javax.swing.JButton();
        btnPasarNivel5 = new javax.swing.JButton();
        btnPasarNivel6 = new javax.swing.JButton();
        btnPasarNivel7 = new javax.swing.JButton();
        pnlDGrados = new javax.swing.JPanel();
        lblTituloIGrados = new javax.swing.JLabel();
        lblGradoActual = new javax.swing.JLabel();
        btnPasarNivel1 = new javax.swing.JButton();
        btnPasarNivel8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setResizable(false);

        pnlGrado.setBackground(new java.awt.Color(123, 211, 200));
        pnlGrado.setPreferredSize(new java.awt.Dimension(1200, 600));
        pnlGrado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloGrados.setFont(new java.awt.Font("Walkway UltraBold", 0, 36)); // NOI18N
        lblTituloGrados.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloGrados.setText("Grados ");
        pnlGrado.add(lblTituloGrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 150, 96));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/paper56.png"))); // NOI18N
        pnlGrado.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, -1, 430));

        slptGrados.setBackground(new java.awt.Color(255, 255, 255));
        slptGrados.setBorder(null);
        slptGrados.setDividerLocation(385);

        pnlIGrados.setBackground(new java.awt.Color(123, 211, 200));
        pnlIGrados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Walkway UltraBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Grados Disponibles");
        pnlIGrados.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 50));

        btnPasarNivel2.setBackground(new java.awt.Color(199, 13, 13));
        btnPasarNivel2.setFont(new java.awt.Font("Fairview Small Caps", 0, 24)); // NOI18N
        btnPasarNivel2.setForeground(new java.awt.Color(255, 255, 255));
        btnPasarNivel2.setText("Sexto Grado");
        btnPasarNivel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPasarNivel2.setBorderPainted(false);
        btnPasarNivel2.setContentAreaFilled(false);
        btnPasarNivel2.setFocusPainted(false);
        btnPasarNivel2.setOpaque(true);
        pnlIGrados.add(btnPasarNivel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 140, 50));

        btnPasarNivel3.setBackground(new java.awt.Color(199, 13, 13));
        btnPasarNivel3.setFont(new java.awt.Font("Fairview Small Caps", 0, 24)); // NOI18N
        btnPasarNivel3.setForeground(new java.awt.Color(255, 255, 255));
        btnPasarNivel3.setText("Primer Grado");
        btnPasarNivel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPasarNivel3.setBorderPainted(false);
        btnPasarNivel3.setContentAreaFilled(false);
        btnPasarNivel3.setFocusPainted(false);
        btnPasarNivel3.setOpaque(true);
        pnlIGrados.add(btnPasarNivel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 140, 50));

        btnPasarNivel4.setBackground(new java.awt.Color(199, 13, 13));
        btnPasarNivel4.setFont(new java.awt.Font("Fairview Small Caps", 0, 24)); // NOI18N
        btnPasarNivel4.setForeground(new java.awt.Color(255, 255, 255));
        btnPasarNivel4.setText("Segundo Grado");
        btnPasarNivel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPasarNivel4.setBorderPainted(false);
        btnPasarNivel4.setContentAreaFilled(false);
        btnPasarNivel4.setFocusPainted(false);
        btnPasarNivel4.setOpaque(true);
        pnlIGrados.add(btnPasarNivel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 140, 50));

        btnPasarNivel5.setBackground(new java.awt.Color(199, 13, 13));
        btnPasarNivel5.setFont(new java.awt.Font("Fairview Small Caps", 0, 24)); // NOI18N
        btnPasarNivel5.setForeground(new java.awt.Color(255, 255, 255));
        btnPasarNivel5.setText("Tercer Grado");
        btnPasarNivel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPasarNivel5.setBorderPainted(false);
        btnPasarNivel5.setContentAreaFilled(false);
        btnPasarNivel5.setFocusPainted(false);
        btnPasarNivel5.setOpaque(true);
        pnlIGrados.add(btnPasarNivel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 140, 50));

        btnPasarNivel6.setBackground(new java.awt.Color(199, 13, 13));
        btnPasarNivel6.setFont(new java.awt.Font("Fairview Small Caps", 0, 24)); // NOI18N
        btnPasarNivel6.setForeground(new java.awt.Color(255, 255, 255));
        btnPasarNivel6.setText("Cuarto Grado");
        btnPasarNivel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPasarNivel6.setBorderPainted(false);
        btnPasarNivel6.setContentAreaFilled(false);
        btnPasarNivel6.setFocusPainted(false);
        btnPasarNivel6.setOpaque(true);
        pnlIGrados.add(btnPasarNivel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 140, 50));

        btnPasarNivel7.setBackground(new java.awt.Color(199, 13, 13));
        btnPasarNivel7.setFont(new java.awt.Font("Fairview Small Caps", 0, 24)); // NOI18N
        btnPasarNivel7.setForeground(new java.awt.Color(255, 255, 255));
        btnPasarNivel7.setText("Quinto Grado");
        btnPasarNivel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPasarNivel7.setBorderPainted(false);
        btnPasarNivel7.setContentAreaFilled(false);
        btnPasarNivel7.setFocusPainted(false);
        btnPasarNivel7.setOpaque(true);
        pnlIGrados.add(btnPasarNivel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 140, 50));

        slptGrados.setLeftComponent(pnlIGrados);

        pnlDGrados.setBackground(new java.awt.Color(123, 211, 200));
        pnlDGrados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloIGrados.setFont(new java.awt.Font("Walkway UltraBold", 0, 36)); // NOI18N
        lblTituloIGrados.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloIGrados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloIGrados.setText("Grado Actual");
        pnlDGrados.add(lblTituloIGrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 310, 60));

        lblGradoActual.setFont(new java.awt.Font("Walkway UltraBold", 0, 36)); // NOI18N
        lblGradoActual.setForeground(new java.awt.Color(102, 102, 102));
        lblGradoActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGradoActual.setText("3°");
        pnlDGrados.add(lblGradoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 90, 50));

        btnPasarNivel1.setBackground(new java.awt.Color(199, 13, 13));
        btnPasarNivel1.setFont(new java.awt.Font("Fairview Small Caps", 0, 24)); // NOI18N
        btnPasarNivel1.setForeground(new java.awt.Color(255, 255, 255));
        btnPasarNivel1.setText("Salir");
        btnPasarNivel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPasarNivel1.setBorderPainted(false);
        btnPasarNivel1.setContentAreaFilled(false);
        btnPasarNivel1.setFocusPainted(false);
        btnPasarNivel1.setOpaque(true);
        btnPasarNivel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasarNivel1ActionPerformed(evt);
            }
        });
        pnlDGrados.add(btnPasarNivel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 180, 40));

        btnPasarNivel8.setBackground(new java.awt.Color(199, 13, 13));
        btnPasarNivel8.setFont(new java.awt.Font("Fairview Small Caps", 0, 24)); // NOI18N
        btnPasarNivel8.setForeground(new java.awt.Color(255, 255, 255));
        btnPasarNivel8.setText("Pasar De Nivel");
        btnPasarNivel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPasarNivel8.setBorderPainted(false);
        btnPasarNivel8.setContentAreaFilled(false);
        btnPasarNivel8.setFocusPainted(false);
        btnPasarNivel8.setOpaque(true);
        pnlDGrados.add(btnPasarNivel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 190, 70));

        slptGrados.setRightComponent(pnlDGrados);

        pnlGrado.add(slptGrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, 480));

        jLabel2.setFont(new java.awt.Font("olivier", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/olympic.png"))); // NOI18N
        jLabel2.setText("Learn With Gerry");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlGrado.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 510, 130, 90));

        getContentPane().add(pnlGrado, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPasarNivel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasarNivel1ActionPerformed
        this.dispose();
        PerfilJugador perfil = new PerfilJugador();
        perfil.setVisible(true);
    }//GEN-LAST:event_btnPasarNivel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Grado dialog = new Grado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPasarNivel1;
    private javax.swing.JButton btnPasarNivel2;
    private javax.swing.JButton btnPasarNivel3;
    private javax.swing.JButton btnPasarNivel4;
    private javax.swing.JButton btnPasarNivel5;
    private javax.swing.JButton btnPasarNivel6;
    private javax.swing.JButton btnPasarNivel7;
    private javax.swing.JButton btnPasarNivel8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblGradoActual;
    private javax.swing.JLabel lblTituloGrados;
    private javax.swing.JLabel lblTituloIGrados;
    private javax.swing.JPanel pnlDGrados;
    private javax.swing.JPanel pnlGrado;
    private javax.swing.JPanel pnlIGrados;
    private javax.swing.JSplitPane slptGrados;
    // End of variables declaration//GEN-END:variables
}
